// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpQMvjriI4Rsq3RoA6wqzmSg_9OxjkHK8',
    appId: '1:305568589097:web:6b0a8309bde9d8e1688338',
    messagingSenderId: '305568589097',
    projectId: 'idpassglobal-app',
    authDomain: 'idpassglobal-app.firebaseapp.com',
    storageBucket: 'idpassglobal-app.firebasestorage.app',
    measurementId: 'G-JPR5E8EQ3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJZrh3UUfX5vZWUfkLwdZuv-LticpTwRo',
    appId: '1:305568589097:android:0337757b9701a382688338',
    messagingSenderId: '305568589097',
    projectId: 'idpassglobal-app',
    storageBucket: 'idpassglobal-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4PhZiDNbPjKTmw9f3hPDPBPPUnMWy0Z4',
    appId: '1:305568589097:ios:711a9ffe070ef787688338',
    messagingSenderId: '305568589097',
    projectId: 'idpassglobal-app',
    storageBucket: 'idpassglobal-app.firebasestorage.app',
    iosBundleId: 'com.example.workapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4PhZiDNbPjKTmw9f3hPDPBPPUnMWy0Z4',
    appId: '1:305568589097:ios:711a9ffe070ef787688338',
    messagingSenderId: '305568589097',
    projectId: 'idpassglobal-app',
    storageBucket: 'idpassglobal-app.firebasestorage.app',
    iosBundleId: 'com.example.workapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpQMvjriI4Rsq3RoA6wqzmSg_9OxjkHK8',
    appId: '1:305568589097:web:4e9024c191acbecc688338',
    messagingSenderId: '305568589097',
    projectId: 'idpassglobal-app',
    authDomain: 'idpassglobal-app.firebaseapp.com',
    storageBucket: 'idpassglobal-app.firebasestorage.app',
    measurementId: 'G-ETP9V0G1BZ',
  );
}
